#!/bin/env bash

set -eo pipefail

source "$(dirname $0)/stats-utils.sh"

shrink() {
    echo "$(sum $1)" > "$1"
}

for user in "$(get-traffic-data-directory)"/*; do
    shrink "$user/down/$(date +%F)"
    shrink "$user/up/$(date +%F)"
done
