#!/bin/env bash

set -eo pipefail

source "$(dirname $0)/stats-utils.sh"

shrink() {
    echo "$(sum-num-file $1)" > "$1"
}

for user in "$TRAFFIC_DIR"/*; do
    shrink "$user/down/$(date +%F)"
    shrink "$user/up/$(date +%F)"
done
