#!/bin/env bash

set -eo pipefail

source "$(dirname $0)/stats-utils.sh"

plain_output=false
if [ "$1" == "--plain" ]; then
    plain_output=true
    shift
fi

ddate=${1:-$(date +%F)}

if [ "$plain_output" = true ]; then
    echo "user down_mb up_mb"
else
    echo -e "\033[1;33mDate:  \033[1;0m$ddate\033[1;0m"
    echo
    echo -e "           \033[1;34m↓ down (mb) \033[1;32m↑ up (mb)\033[1;0m"
fi

for user in "$(get-traffic-data-directory)"/*; do
    down=$(sum "$user/down/$ddate")
    up=$(sum "$user/up/$ddate")

    down=${down:-0}
    up=${up:-0}

    downMb=$(echo "scale=0; $down / 1024 / 1024" | bc)
    upMb=$(echo "scale=0; $up / 1024 / 1024" | bc)

    if [ "$plain_output" = true ]; then
        echo "$(basename "$user") $downMb $upMb"
    else
        printf "%-10s \033[1;34m%10s \033[1;32m%10s\033[1;0m\n" \
            "$(basename "$user")" "$downMb" "$upMb"
    fi
done
