#!/bin/env bash

set -eo pipefail

source "$(dirname "$0")/stats-utils.sh"

isPlainOutput=false
if [ "$1" == "--plain" ]; then
    isPlainOutput=true
    shift
fi

print-header() {
    queryUser=$1
    queryDate=$2

    if [ "$isPlainOutput" = true ]; then
        return
    fi

    echo -e "\033[1;33m$queryUser:  \033[1;0m$queryDate\033[1;0m"
    echo
    echo -e "           \033[1;34m↓ down (mb) \033[1;32m↑ up (mb)\033[1;0m"
}

print-user-stats() {
    local username=$1
    local down=${2:-0}
    local up=${3:-0}

    if [ "$isPlainOutput" = true ]; then
        echo "$username $down $up"
        return
    fi

    local downMb=$((down / 1024 / 1024))
    local upMb=$((up / 1024 / 1024))
    printf "%-10s \033[1;34m%10s \033[1;32m%10s\033[1;0m\n" "$username" "$downMb" "$upMb"
}

query() {
    local queryUser=${1:-*}
    local queryDate="$2"

    print-header "$queryUser" "$queryDate"

    for userDir in "$TRAFFIC_DIR"/$queryUser; do
        username=$(basename "$userDir")
        down=$(sum-num-file "$userDir/down/$queryDate")
        up=$(sum-num-file "$userDir/up/$queryDate")

        print-user-stats "$username" "$down" "$up"
    done
}

query-monthly() {
    local queryUser=${1:-*}
    local queryDate="$2"

    print-header "$queryUser" "$queryDate"

    for userDir in "$TRAFFIC_DIR"/$queryUser; do
        username=$(basename "$userDir")
        local down=0
        local up=0

        for day in "$userDir/down/$queryDate-"*; do
            if [[ ! -f "$day" ]]; then
                continue
            fi

            day=$(basename "$day")
            down=$((down + $(sum-num-file "$userDir/down/$day")))
            up=$((up + $(sum-num-file "$userDir/up/$day")))
        done

        print-user-stats "$username" "$down" "$up"
    done
}


queryDate=${1:-$(date +%F)}
queryUser="${2:-*}"

if [[ "$queryDate" =~ ^[0-9]{4}-[0-9]{2}$ ]]; then
    query-monthly "$queryUser" "$queryDate"
    exit
fi

query "$queryUser" "$queryDate"
